### ISSUE TITLE
Add a screenshot

### ISSUE THREAD

**Issue by maxlorenz** [fabianbormann/Coineda#20]
Would be nice to see a screenshot in the README

**Comment by fabianbormann** [comment]
![coineda-screens](https://user-images.githubusercontent.com/1525818/140197814-83013769-8de1-4496-8bac-a0e6feac19fd.gif)

**Comment by fabianbormann** [comment]
<img width="990" alt="Bildschirmfoto 2023-02-04 um 22 49 24" src="https://user-images.githubusercontent.com/1525818/216790986-e30ac617-bef3-4521-b6c6-6b5bf1f08897.png">

**Comment by fabianbormann** [comment]
![Bildschirmfoto 2023-02-04 um 22 49 24](https://user-images.githubusercontent.com/1525818/216791075-507cc5ca-9cca-4b39-9f1d-690af6c08d2a.png)
